### ISSUE TITLE
how to exit check term size

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/2048#1]
![image](https://github.com/longtoZ/2048/assets/86353526/846402f3-276f-470b-a163-97a07190a387)

how to exit check term size
<kbd>Ctrl</kbd> + <kbd>c</kbd> doesn't work. Neither with <kbd>q</kbd> nor <kbd>ESC</kbd>

**Comment by longtoZ** [comment]
> ![image](https://private-user-images.githubusercontent.com/86353526/341651488-846402f3-276f-470b-a163-97a07190a387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODY0MDMsIm5iZiI6MTcxODk4NjEwMywicGF0aCI6Ii84NjM1MzUyNi8zNDE2NTE0ODgtODQ2NDAyZjMtMjc2Zi00NzBiLWExNjMtOTdhMDcxOTBhMzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE2MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2N2NlNTM4ZTE4MjBjNjEzZTk4M2ZhMDY4OThkZDNlODgyMDU3MGIzMGEwZDNlNzIyYjc1MWVlYjEwZTJhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJfJ_-1vPdcWO_LvtmIxPRtutx5ss5BdTBivL8jirSU)
> 
> how to exit check term size Ctrl + c doesn't work. Neither with q nor ESC

Ko đc đâu bro ((:: Chơi là chơi

**Comment by KevinNitroG** [comment]
> > ![image](https://private-user-images.githubusercontent.com/86353526/341651488-846402f3-276f-470b-a163-97a07190a387.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODY0MDMsIm5iZiI6MTcxODk4NjEwMywicGF0aCI6Ii84NjM1MzUyNi8zNDE2NTE0ODgtODQ2NDAyZjMtMjc2Zi00NzBiLWExNjMtOTdhMDcxOTBhMzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE2MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2N2NlNTM4ZTE4MjBjNjEzZTk4M2ZhMDY4OThkZDNlODgyMDU3MGIzMGEwZDNlNzIyYjc1MWVlYjEwZTJhYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJfJ_-1vPdcWO_LvtmIxPRtutx5ss5BdTBivL8jirSU)
> > how to exit check term size Ctrl + c doesn't work. Neither with q nor ESC
> 
> Ko đc đâu bro ((:: Chơi là chơi

Gì kì vậy wtf =))
