### ISSUE TITLE
no number generation when pressing the same key over some times

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/2048#2]
https://github.com/longtoZ/2048/assets/86353526/15517418-2e7d-4dd1-8c47-38c9ab396cd5

Ye
.-.

**Comment by longtoZ** [comment]
> 2024-06-21_12-39-00.mp4 
> Ye .-.

Vì nó ko di chuyển (bảng ko thay đổi) nên ko tạo số mới bro

**Comment by KevinNitroG** [comment]
> > 2024-06-21_12-39-00.mp4
> > Ye .-.
> 
> Vì nó ko di chuyển (bảng ko thay đổi) nên ko tạo số mới bro

Ủa có cái logic này luôn hả bro
:))

**Comment by longtoZ** [comment]
> > > 2024-06-21_12-39-00.mp4
> > > Ye .-.
> > 
> > 
> > Vì nó ko di chuyển (bảng ko thay đổi) nên ko tạo số mới bro
> 
> Ủa có cái logic này luôn hả bro :))

Chơi game nó vậy mà ((::

**Comment by KevinNitroG** [comment]
Ủa reopen issue chi dậy :))

**Comment by longtoZ** [comment]
> Ủa reopen issue chi dậy :))

Ủa chắc nhầm ((=
